FROM openjdk:17-alpine

RUN apk add --no-cache bash && \
    apk add --no-cache htop 

RUN mvn -DskipTests package

WORKDIR /app


COPY target/*.jar /app/api.jar
COPY wait-for-it.sh /wait-for-it.sh

ARG CACHEBUST=0

RUN chmod +x /wait-for-it.sh


EXPOSE 8080


CMD [ "java", "-XX:MaxRAM=72m","-server", "-Xss512k", "-XX:+UseSerialGC", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap","-Dspring.profiles.active=prod", "-jar", "api.jar"]