insert into cozinha (nome) values ('afegane ou afegão');
insert into cozinha (nome) values ('sul-africano ou austro-africano');
insert into cozinha (nome) values ('albanês');
insert into cozinha (nome) values ('alemão, germânico, germano ou teutônico');
insert into cozinha (nome) values ('andorrano ou andorrense');
insert into cozinha (nome) values ('angolano ou angolense');
insert into cozinha (nome) values ('antiguano');
insert into cozinha (nome) values ('saudita, árabe-saudita');
insert into cozinha (nome) values ('argelino ou argeliano');
insert into cozinha (nome) values ('argentino');
insert into cozinha (nome) values ('australiano, australês ou austrálio');
insert into cozinha (nome) values ('austríaco');
insert into cozinha (nome) values ('azerbaijano, azeri');
insert into cozinha (nome) values ('bahamense, baamense, baamês, baamiano ou bahamiano');
insert into cozinha (nome) values ('bangladeshiano');
insert into cozinha (nome) values ('barbadiano');
insert into cozinha (nome) values ('belga');
insert into cozinha (nome) values ('belizenho ou belizense');
insert into cozinha (nome) values ('beninense');
insert into cozinha (nome) values ('bielo-russo');
insert into cozinha (nome) values ('birmanês, birmã, birmane ou mianmarense');
insert into cozinha (nome) values ('boliviano');
insert into cozinha (nome) values ('bósnio');
insert into cozinha (nome) values ('botsuanense ou botsuanês');
insert into cozinha (nome) values ('brasileiro ou brasiliano');
insert into cozinha (nome) values ('bruneano');
insert into cozinha (nome) values ('búlgaro');
insert into cozinha (nome) values ('burquinense, burquinabê ou burquino');
insert into cozinha (nome) values ('burundiano, burundinês');
insert into cozinha (nome) values ('butanês, butanense, butâni ou butani');
insert into cozinha (nome) values ('cabo-verdiano');
insert into cozinha (nome) values ('camaronense ou camaronês');
insert into cozinha (nome) values ('cambojano, cambojiano ou campucheano');
insert into cozinha (nome) values ('canadense, canadiano ou canadiense');
insert into cozinha (nome) values ('catariano ou catarense');
insert into cozinha (nome) values ('cazaquistanês');
insert into cozinha (nome) values ('chadiano ou chadiense');
insert into cozinha (nome) values ('chileno');
insert into cozinha (nome) values ('chinês, china, chim ou chino');
insert into cozinha (nome) values ('cipriota, cíprio ou chiprense');
insert into cozinha (nome) values ('colombiano');
insert into cozinha (nome) values ('comorense ou comoriano');
insert into cozinha (nome) values ('congolês, congo ou conguês');
insert into cozinha (nome) values ('coreano, norte-coreano');
insert into cozinha (nome) values ('coreano, sul-coreano');
insert into cozinha (nome) values ('marfiniano, marfinense, ebúrneo ou costa-marfinense');
insert into cozinha (nome) values ('costa-riquenho ou costa-riquense');
insert into cozinha (nome) values ('croata');
insert into cozinha (nome) values ('cubano');
insert into cozinha (nome) values ('dinamarquês, danês ou dano');
insert into cozinha (nome) values ('djibutiano');
insert into cozinha (nome) values ('egípcio, egipcíaco ou egipciano');
insert into cozinha (nome) values ('salvadorenho ou salvatoriano');
insert into cozinha (nome) values ('emiradense');
insert into cozinha (nome) values ('equatoriano');
insert into cozinha (nome) values ('escocês');
insert into cozinha (nome) values ('eslovaco');
insert into cozinha (nome) values ('espanhol');
insert into cozinha (nome) values ('norte-americano, estadunidense, americano, ianque, americano-do-norte ou estado-unidense');
insert into cozinha (nome) values ('estoniano ou estônio');
insert into cozinha (nome) values ('esloveno');
insert into cozinha (nome) values ('etíope ou etiópio');
insert into cozinha (nome) values ('fijiano, fidjiano');
insert into cozinha (nome) values ('filipino');
insert into cozinha (nome) values ('finlandês ou finês');
insert into cozinha (nome) values ('francês');
insert into cozinha (nome) values ('gabonense ou gabonês');
insert into cozinha (nome) values ('gambiano ou gambiense');
insert into cozinha (nome) values ('ganense ou ganês');
insert into cozinha (nome) values ('georgiano');
insert into cozinha (nome) values ('granadino');
insert into cozinha (nome) values ('grego, heleno ou argivo');
insert into cozinha (nome) values ('groenlandês ou gronelandês');
insert into cozinha (nome) values ('guatemalteco ou guatemalense');
insert into cozinha (nome) values ('guianense ou guianês');
insert into cozinha (nome) values ('guineano ou guinéu');
insert into cozinha (nome) values ('guineense');
insert into cozinha (nome) values ('guinéu-equatoriano');
insert into cozinha (nome) values ('haitiano');
insert into cozinha (nome) values ('holandês, neerlandês ou batavo');
insert into cozinha (nome) values ('hondurenho');
insert into cozinha (nome) values ('húngaro ou hungarês');
insert into cozinha (nome) values ('iemenita');
insert into cozinha (nome) values ('marshalino');
insert into cozinha (nome) values ('salomônico');
insert into cozinha (nome) values ('indiano, índio, índu ou hindu');
insert into cozinha (nome) values ('Indonésia');
insert into cozinha (nome) values ('inglês, anglo, anglo-saxão ou britânico');
insert into cozinha (nome) values ('iraniano ou irânico');
insert into cozinha (nome) values ('iraquiano');
insert into cozinha (nome) values ('irlandês');
insert into cozinha (nome) values ('islandês');
insert into cozinha (nome) values ('israelense ou israeliano, israelita (relativo à religião)');
insert into cozinha (nome) values ('italiano, itálico ou ítalo');
insert into cozinha (nome) values ('iugoslavo ou iugoslavo');
insert into cozinha (nome) values ('jamaicano ou jamaicense');
insert into cozinha (nome) values ('japonês ou nipônico');
insert into cozinha (nome) values ('jordaniano, jordaniense ou jordânio');
insert into cozinha (nome) values ('kiribatiano');
insert into cozinha (nome) values ('kuwaitiano');
insert into cozinha (nome) values ('laosiano ou laosense');
insert into cozinha (nome) values ('lesotiano');
insert into cozinha (nome) values ('libanês');
insert into cozinha (nome) values ('liberiano');
insert into cozinha (nome) values ('líbio ou líbico');
insert into cozinha (nome) values ('liechtensteinense, liechtensteiniano, liechtensteiniense ou listenstainiano');
insert into cozinha (nome) values ('luxemburguês');
insert into cozinha (nome) values ('macedônio');
insert into cozinha (nome) values ('malásio, malaio ou malasiano');
insert into cozinha (nome) values ('malaviano ou malauiano');
insert into cozinha (nome) values ('maldívio, maldivano, maldiviano ou maldivo');
insert into cozinha (nome) values ('maliano');
insert into cozinha (nome) values ('maltês');
insert into cozinha (nome) values ('marroquino');
insert into cozinha (nome) values ('mauriciano');
insert into cozinha (nome) values ('mauritaniano ou mauritano');
insert into cozinha (nome) values ('mexicano');
insert into cozinha (nome) values ('moçambicano');
insert into cozinha (nome) values ('moldávio');
insert into cozinha (nome) values ('monegasco');
insert into cozinha (nome) values ('mongol, mongolino ou mongólico');
insert into cozinha (nome) values ('birmane, birmanês ou birmã');
insert into cozinha (nome) values ('namibiano ou namíbio');
insert into cozinha (nome) values ('nauruano');
insert into cozinha (nome) values ('nepalês');
insert into cozinha (nome) values ('nicaraguano ou nicaraguense');
insert into cozinha (nome) values ('nigerino ou nigerense');
insert into cozinha (nome) values ('nigeriano');
insert into cozinha (nome) values ('norueguês');
insert into cozinha (nome) values ('neozelandês');
insert into cozinha (nome) values ('omanense, omaniano ou omani');
insert into cozinha (nome) values ('palauano, palauense');
insert into cozinha (nome) values ('panamenho ou panamense');
insert into cozinha (nome) values ('papua ou papuásio');
insert into cozinha (nome) values ('paquistanense ou paquistanês');
insert into cozinha (nome) values ('paraguaio ou paraguaiano');
insert into cozinha (nome) values ('peruano ou peruviano');
insert into cozinha (nome) values ('polonês ou polaco');
insert into cozinha (nome) values ('porto-riquenho ou porto-riquense');
insert into cozinha (nome) values ('português, lusitano ou luso');
insert into cozinha (nome) values ('queniano');
insert into cozinha (nome) values ('quirguistanês, quirguiz');
insert into cozinha (nome) values ('centro-africano');
insert into cozinha (nome) values ('checo');
insert into cozinha (nome) values ('dominicano');
insert into cozinha (nome) values ('romeno');
insert into cozinha (nome) values ('ruandês');
insert into cozinha (nome) values ('russo');
insert into cozinha (nome) values ('samoano ou samoense');
insert into cozinha (nome) values ('santa-lucense');
insert into cozinha (nome) values ('são-cristovense');
insert into cozinha (nome) values ('são-marinense ou são-marinense');
insert into cozinha (nome) values ('são-tomense ou santomense');
insert into cozinha (nome) values ('são-vicentino');
insert into cozinha (nome) values ('seichelense ou seychellense');
insert into cozinha (nome) values ('senegalês, senegalense ou senegaliano');
insert into cozinha (nome) values ('serra-leonense ou serra-leonês');
insert into cozinha (nome) values ('singapurense ou singapurano');
insert into cozinha (nome) values ('sírio ou siríaco');
insert into cozinha (nome) values ('somali ou somaliano');
insert into cozinha (nome) values ('cingalês');
insert into cozinha (nome) values ('suazi, suázi ou suazilandês');
insert into cozinha (nome) values ('sudanês');
insert into cozinha (nome) values ('sul-suldanês');
insert into cozinha (nome) values ('sueco');
insert into cozinha (nome) values ('suíço, helvécio ou helvético');
insert into cozinha (nome) values ('surinamense ou surinamês');
insert into cozinha (nome) values ('tailandês');
insert into cozinha (nome) values ('tajique, tajiquistanês');
insert into cozinha (nome) values ('tanzaniano');
insert into cozinha (nome) values ('tibetano');
insert into cozinha (nome) values ('timorense');
insert into cozinha (nome) values ('togolês, togolense, toguense ou toguês');
insert into cozinha (nome) values ('tonganês');
insert into cozinha (nome) values ('trinitário, trinitário-tobagense e tobaguiano');
insert into cozinha (nome) values ('tunisiano');
insert into cozinha (nome) values ('turco');
insert into cozinha (nome) values ('tuvaluano');
insert into cozinha (nome) values ('ucraniano');
insert into cozinha (nome) values ('ugandense ou ugandês');
insert into cozinha (nome) values ('uruguaio ou uruguaiano');
insert into cozinha (nome) values ('uzbeque, uzbequistanês');
insert into cozinha (nome) values ('venezuelano');
insert into cozinha (nome) values ('vietnamita ou vietnamense');
insert into cozinha (nome) values ('zairense');
insert into cozinha (nome) values ('zambiano, zambiense ou zâmbio');
insert into cozinha (nome) values ('zimbabuense ou zimbabuano');