insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteafegane ou afegão',75.38,1);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesul-africano ou austro-africano',6.88,2);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantealbanês',85.24,3);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantealemão, germânico, germano ou teutônico',98.27,4);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteandorrano ou andorrense',40.38,5);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteangolano ou angolense',29.33,6);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteantiguano',66.19,7);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesaudita, árabe-saudita',91.87,8);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteargelino ou argeliano',9.59,9);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteargentino',14.51,10);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteaustraliano, australês ou austrálio',97.89,11);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteaustríaco',94.49,12);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteazerbaijano, azeri',27.51,13);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebahamense, baamense, baamês, baamiano ou bahamiano',97.09,14);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebangladeshiano',61.82,15);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebarbadiano',96.09,16);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebelga',60.01,17);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebelizenho ou belizense',39.92,18);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebeninense',79.61,19);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebielo-russo',30.94,20);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebirmanês, birmã, birmane ou mianmarense',71.52,21);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteboliviano',17.58,22);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebósnio',82.61,23);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebotsuanense ou botsuanês',88.56,24);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebrasileiro ou brasiliano',75.45,25);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebruneano',72.24,26);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebúlgaro',86.74,27);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteburquinense, burquinabê ou burquino',27.18,28);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteburundiano, burundinês',57.08,29);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebutanês, butanense, butâni ou butani',37.99,30);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecabo-verdiano',45.33,31);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecamaronense ou camaronês',26.57,32);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecambojano, cambojiano ou campucheano',78.24,33);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecanadense, canadiano ou canadiense',56.06,34);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecatariano ou catarense',1.9,35);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecazaquistanês',45.6,36);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantechadiano ou chadiense',86.64,37);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantechileno',58.54,38);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantechinês, china, chim ou chino',67.41,39);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecipriota, cíprio ou chiprense',56.07,40);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecolombiano',69.13,41);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecomorense ou comoriano',80.77,42);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecongolês, congo ou conguês',1.78,43);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecoreano, norte-coreano',8.92,44);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecoreano, sul-coreano',7.9,45);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemarfiniano, marfinense, ebúrneo ou costa-marfinense',73.89,46);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecosta-riquenho ou costa-riquense',88.49,47);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecroata',51.54,48);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecubano',21.22,49);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantedinamarquês, danês ou dano',28.03,50);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantedjibutiano',52.7,51);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteegípcio, egipcíaco ou egipciano',55.49,52);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesalvadorenho ou salvatoriano',96.34,53);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteemiradense',83.88,54);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteequatoriano',88.37,55);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteescocês',33.02,56);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteeslovaco',51.13,57);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteespanhol',06.01,58);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantenorte-americano, estadunidense, americano, ianque, americano-do-norte ou estado-unidense',27.78,59);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteestoniano ou estônio',17.44,60);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteesloveno',93.15,61);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteetíope ou etiópio',14.58,62);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantefijiano, fidjiano',8.26,63);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantefilipino',57.81,64);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantefinlandês ou finês',80.11,65);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantefrancês',23.87,66);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantegabonense ou gabonês',65.04,67);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantegambiano ou gambiense',31.38,68);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteganense ou ganês',24.03,69);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantegeorgiano',15.84,70);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantegranadino',6.77,71);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantegrego, heleno ou argivo',8.8,72);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantegroenlandês ou gronelandês',23.02,73);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteguatemalteco ou guatemalense',84.94,74);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteguianense ou guianês',10.54,75);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteguineano ou guinéu',16.32,76);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteguineense',49.08,77);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteguinéu-equatoriano',26.08,78);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantehaitiano',7.4,79);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteholandês, neerlandês ou batavo',26.99,80);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantehondurenho',68.13,81);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantehúngaro ou hungarês',2.29,82);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteiemenita',15.57,83);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemarshalino',78.68,84);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesalomônico',19.45,85);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteindiano, índio, índu ou hindu',20.58,86);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteIndonésia',19.11,87);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteinglês, anglo, anglo-saxão ou britânico',60.19,88);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteiraniano ou irânico',35.57,89);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteiraquiano',64.95,90);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteirlandês',82.29,91);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteislandês',29.17,92);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteisraelense ou israeliano, israelita (relativo à religião)',40.85,93);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteitaliano, itálico ou ítalo',84.17,94);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteiugoslavo ou iugoslavo',36.67,95);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantejamaicano ou jamaicense',25.4,96);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantejaponês ou nipônico',27.32,97);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantejordaniano, jordaniense ou jordânio',8.51,98);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantekiribatiano',76.67,99);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantekuwaitiano',21.15,100);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantelaosiano ou laosense',69.5,101);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantelesotiano',74.33,102);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantelibanês',52.32,103);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteliberiano',6.98,104);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantelíbio ou líbico',6.7,105);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteliechtensteinense, liechtensteiniano, liechtensteiniense ou listenstainiano',68.54,106);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteluxemburguês',53.09,107);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemacedônio',45.44,108);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemalásio, malaio ou malasiano',90.79,109);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemalaviano ou malauiano',65.77,110);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemaldívio, maldivano, maldiviano ou maldivo',35.57,111);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemaliano',38.01,112);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemaltês',70.12,113);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemarroquino',20.34,114);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemauriciano',59.63,115);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemauritaniano ou mauritano',41.23,116);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemexicano',56.23,117);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemoçambicano',92.49,118);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemoldávio',62.5,119);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemonegasco',36.88,120);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantemongol, mongolino ou mongólico',99.15,121);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantebirmane, birmanês ou birmã',33.5,122);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantenamibiano ou namíbio',18.24,123);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantenauruano',7.82,124);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantenepalês',78.78,125);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantenicaraguano ou nicaraguense',28.23,126);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantenigerino ou nigerense',1.56,127);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantenigeriano',96.67,128);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantenorueguês',5.65,129);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteneozelandês',94.85,130);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteomanense, omaniano ou omani',98.86,131);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantepalauano, palauense',27.09,132);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantepanamenho ou panamense',12.25,133);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantepapua ou papuásio',71.59,134);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantepaquistanense ou paquistanês',87.14,135);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteparaguaio ou paraguaiano',49.4,136);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteperuano ou peruviano',7.94,137);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantepolonês ou polaco',78.33,138);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteporto-riquenho ou porto-riquense',31.75,139);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteportuguês, lusitano ou luso',31.32,140);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantequeniano',64.98,141);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantequirguistanês, quirguiz',26.47,142);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecentro-africano',37.84,143);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecheco',52.37,144);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantedominicano',0.86,145);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteromeno',65.21,146);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteruandês',27.04,147);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranterusso',76.23,148);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesamoano ou samoense',23.25,149);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesanta-lucense',94.19,150);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesão-cristovense',0.92,151);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesão-marinense ou são-marinense',69.06,152);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesão-tomense ou santomense',7.61,153);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesão-vicentino',43.22,154);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteseichelense ou seychellense',95.77,155);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesenegalês, senegalense ou senegaliano',3.96,156);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteserra-leonense ou serra-leonês',84.81,157);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesingapurense ou singapurano',18.06,158);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesírio ou siríaco',29.61,159);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesomali ou somaliano',41.65,160);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantecingalês',26.33,161);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesuazi, suázi ou suazilandês',38.12,162);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesudanês',91.39,163);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesul-suldanês',5.77,164);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesueco',27.91,165);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesuíço, helvécio ou helvético',46.56,166);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantesurinamense ou surinamês',24.97,167);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantetailandês',77.57,168);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantetajique, tajiquistanês',9.17,169);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantetanzaniano',56.26,170);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantetibetano',16.08,171);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantetimorense',19.17,172);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantetogolês, togolense, toguense ou toguês',66.2,173);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantetonganês',6.12,174);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantetrinitário, trinitário-tobagense e tobaguiano',98.86,175);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantetunisiano',97.22,176);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteturco',36.91,177);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantetuvaluano',41.49,178);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteucraniano',60.84,179);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteugandense ou ugandês',19.39,180);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteuruguaio ou uruguaiano',64.97,181);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restauranteuzbeque, uzbequistanês',99.4,182);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantevenezuelano',39.69,183);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantevietnamita ou vietnamense',15.26,184);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantezairense',76.87,185);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantezambiano, zambiense ou zâmbio',75.18,186);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurantezimbabuense ou zimbabuano',73.57,187);