insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante afegane ou afegão',75.38,1);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante sul-africano ou austro-africano',6.88,2);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante albanês',85.24,3);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante alemão, germânico, germano ou teutônico',98.27,4);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante andorrano ou andorrense',40.38,5);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante angolano ou angolense',29.33,6);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante antiguano',66.19,7);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante saudita, árabe-saudita',91.87,8);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante argelino ou argeliano',9.59,9);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante argentino',14.51,10);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante australiano, australês ou austrálio',97.89,11);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante austríaco',94.49,12);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante azerbaijano, azeri',27.51,13);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante bahamense, baamense, baamês, baamiano ou bahamiano',97.09,14);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante bangladeshiano',61.82,15);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante barbadiano',96.09,16);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante belga',60.01,17);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante belizenho ou belizense',39.92,18);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante beninense',79.61,19);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante bielo-russo',30.94,20);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante birmanês, birmã, birmane ou mianmarense',71.52,21);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante boliviano',17.58,22);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante bósnio',82.61,23);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante botsuanense ou botsuanês',88.56,24);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante brasileiro ou brasiliano',75.45,25);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante bruneano',72.24,26);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante búlgaro',86.74,27);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante burquinense, burquinabê ou burquino',27.18,28);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante burundiano, burundinês',57.08,29);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante butanês, butanense, butâni ou butani',37.99,30);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante cabo-verdiano',45.33,31);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante camaronense ou camaronês',26.57,32);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante cambojano, cambojiano ou campucheano',78.24,33);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante canadense, canadiano ou canadiense',56.06,34);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante catariano ou catarense',1.9,35);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante cazaquistanês',45.6,36);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante chadiano ou chadiense',86.64,37);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante chileno',58.54,38);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante chinês, china, chim ou chino',67.41,39);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante cipriota, cíprio ou chiprense',56.07,40);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante colombiano',69.13,41);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante comorense ou comoriano',80.77,42);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante congolês, congo ou conguês',1.78,43);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante coreano, norte-coreano',8.92,44);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante coreano, sul-coreano',7.9,45);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante marfiniano, marfinense, ebúrneo ou costa-marfinense',73.89,46);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante costa-riquenho ou costa-riquense',88.49,47);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante croata',51.54,48);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante cubano',21.22,49);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante dinamarquês, danês ou dano',28.03,50);

insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante djibutiano',52.7,51);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante egípcio, egipcíaco ou egipciano',55.49,52);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante salvadorenho ou salvatoriano',96.34,53);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante emiradense',83.88,54);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante equatoriano',88.37,55);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante escocês',33.02,56);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante eslovaco',51.13,57);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante espanhol',06.01,58);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante norte-americano, estadunidense, americano, ianque, americano-do-norte ou estado-unidense',27.78,59);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante estoniano ou estônio',17.44,60);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante esloveno',93.15,61);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante etíope ou etiópio',14.58,62);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante fijiano, fidjiano',8.26,63);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante filipino',57.81,64);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante finlandês ou finês',80.11,65);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante francês',23.87,66);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante gabonense ou gabonês',65.04,67);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante gambiano ou gambiense',31.38,68);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante ganense ou ganês',24.03,69);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante georgiano',15.84,70);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante granadino',6.77,71);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante grego, heleno ou argivo',8.8,72);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante groenlandês ou gronelandês',23.02,73);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante guatemalteco ou guatemalense',84.94,74);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante guianense ou guianês',10.54,75);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante guineano ou guinéu',16.32,76);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante guineense',49.08,77);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante guinéu-equatoriano',26.08,78);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante haitiano',7.4,79);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante holandês, neerlandês ou batavo',26.99,80);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante hondurenho',68.13,81);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante húngaro ou hungarês',2.29,82);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante iemenita',15.57,83);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante marshalino',78.68,84);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante salomônico',19.45,85);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante indiano, índio, índu ou hindu',20.58,86);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante Indonésia',19.11,87);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante inglês, anglo, anglo-saxão ou britânico',60.19,88);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante iraniano ou irânico',35.57,89);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante iraquiano',64.95,90);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante irlandês',82.29,91);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante islandês',29.17,92);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante israelense ou israeliano, israelita (relativo à religião)',40.85,93);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante italiano, itálico ou ítalo',84.17,94);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante iugoslavo ou iugoslavo',36.67,95);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante jamaicano ou jamaicense',25.4,96);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante japonês ou nipônico',27.32,97);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante jordaniano, jordaniense ou jordânio',8.51,98);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante kiribatiano',76.67,99);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante kuwaitiano',21.15,100);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante laosiano ou laosense',69.5,101);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante lesotiano',74.33,102);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante libanês',52.32,103);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante liberiano',6.98,104);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante líbio ou líbico',6.7,105);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante liechtensteinense, liechtensteiniano, liechtensteiniense ou listenstainiano',68.54,106);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante luxemburguês',53.09,107);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante macedônio',45.44,108);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante malásio, malaio ou malasiano',90.79,109);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante malaviano ou malauiano',65.77,110);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante maldívio, maldivano, maldiviano ou maldivo',35.57,111);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante maliano',38.01,112);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante maltês',70.12,113);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante marroquino',20.34,114);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante mauriciano',59.63,115);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante mauritaniano ou mauritano',41.23,116);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante mexicano',56.23,117);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante moçambicano',92.49,118);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante moldávio',62.5,119);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante monegasco',36.88,120);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante mongol, mongolino ou mongólico',99.15,121);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante birmane, birmanês ou birmã',33.5,122);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante namibiano ou namíbio',18.24,123);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante nauruano',7.82,124);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante nepalês',78.78,125);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante nicaraguano ou nicaraguense',28.23,126);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante nigerino ou nigerense',1.56,127);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante nigeriano',96.67,128);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante norueguês',5.65,129);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante neozelandês',94.85,130);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante omanense, omaniano ou omani',98.86,131);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante palauano, palauense',27.09,132);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante panamenho ou panamense',12.25,133);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante papua ou papuásio',71.59,134);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante paquistanense ou paquistanês',87.14,135);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante paraguaio ou paraguaiano',49.4,136);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante peruano ou peruviano',7.94,137);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante polonês ou polaco',78.33,138);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante porto-riquenho ou porto-riquense',31.75,139);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante português, lusitano ou luso',31.32,140);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante queniano',64.98,141);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante quirguistanês, quirguiz',26.47,142);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante centro-africano',37.84,143);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante checo',52.37,144);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante dominicano',0.86,145);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante romeno',65.21,146);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante ruandês',27.04,147);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante russo',76.23,148);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante samoano ou samoense',23.25,149);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante santa-lucense',94.19,150);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante são-cristovense',0.92,151);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante são-marinense ou são-marinense',69.06,152);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante são-tomense ou santomense',7.61,153);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante são-vicentino',43.22,154);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante seichelense ou seychellense',95.77,155);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante senegalês, senegalense ou senegaliano',3.96,156);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante serra-leonense ou serra-leonês',84.81,157);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante singapurense ou singapurano',18.06,158);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante sírio ou siríaco',29.61,159);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante somali ou somaliano',41.65,160);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante cingalês',26.33,161);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante suazi, suázi ou suazilandês',38.12,162);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante sudanês',91.39,163);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante sul-suldanês',5.77,164);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante sueco',27.91,165);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante suíço, helvécio ou helvético',46.56,166);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante surinamense ou surinamês',24.97,167);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante tailandês',77.57,168);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante tajique, tajiquistanês',9.17,169);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante tanzaniano',56.26,170);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante tibetano',16.08,171);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante timorense',19.17,172);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante togolês, togolense, toguense ou toguês',66.2,173);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante tonganês',6.12,174);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante trinitário, trinitário-tobagense e tobaguiano',98.86,175);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante tunisiano',97.22,176);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante turco',36.91,177);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante tuvaluano',41.49,178);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante ucraniano',60.84,179);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante ugandense ou ugandês',19.39,180);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante uruguaio ou uruguaiano',64.97,181);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante uzbeque, uzbequistanês',99.4,182);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante venezuelano',39.69,183);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante vietnamita ou vietnamense',15.26,184);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante zairense',76.87,185);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante zambiano, zambiense ou zâmbio',75.18,186);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('restaurante zimbabuense ou zimbabuano',73.57,187);